apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: gitops-with-tap
  labels:
    app.kubernetes.io/part-of: hello-world
    carto.run/workload-name: gitops-with-tap
    app.kubernetes.io/component: run
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '1'
    spec:
      containers:
        - name: workload
          image: harbor.eks.vrabbi.cloud/demo/tap-gitops-gitops-with-tap@sha256:a6abad88aab2f8e3c4537b466ddad8260c39a21706678218898b7b51fdc40bef
          securityContext:
            runAsUser: 1000
      imagePullSecrets:
        - name: registry-credentials-gitops

