apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: python-demo-app
  labels:carto.run/workload-name: python-demo-app
    app.kubernetes.io/component: run
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '1'
    spec:
      containers:
        - name: workload
          image: harbor.vrabbi.cloud/workloads/oss-python-demo-app@sha256:6ab6e0ce55c1553dd55c4b654f8565a34febacd8ac26b4286f42f4bb674f2b2b
          securityContext:
            runAsUser: 1000
      imagePullSecrets:
        - name: registry-credentials

