apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: test-web-app
  labels:
    app.kubernetes.io/part-of: hello-world
    carto.run/workload-name: test-web-app
    app.kubernetes.io/component: run
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '1'
    spec:
      containers:
        - name: workload
          image: harbor.eks.vrabbi.cloud/demo/tap-gitops-test-web-app@sha256:c6005e26211f12c72ffd7ac8dd43f1227f2f0cd1294d91b8f3c29e2493c34e0f
          securityContext:
            runAsUser: 1000
      imagePullSecrets:
        - name: registry-credentials

