apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: go-web-app-gitops
  labels:
    app.kubernetes.io/part-of: hello-world
    carto.run/workload-name: go-web-app-gitops
    app.kubernetes.io/component: run
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '1'
    spec:
      containers:
        - name: workload
          image: harbor.eks.vrabbi.cloud/demo/tap-gitops-go-web-app-gitops@sha256:6b4241f96dd9e4839b592c5822e6292cbb5cd25c6020a46fd3ea9ea2d2d53e3b
          securityContext:
            runAsUser: 1000
      imagePullSecrets:
        - name: registry-credentials-gitops

