apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: sensors-rmq
spec:
  service:
    apiVersion: rabbitmq.com/v1beta1
    kind: RabbitmqCluster
    name: rabbitmqcluster-sample
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: sensors
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sensors
  labels:
    carto.run/workload-name: sensors
    app.kubernetes.io/component: run
spec:
  template:
    spec:
      containers:
      - name: workload
        image: harbor.vrabbi.cloud/workloads/oss-sensors@sha256:5c927a8bdab2c8e5f4db542e05af94a6b16397b6477a6ace48482e3e3fc13590
        securityContext:
          runAsUser: 1000
      imagePullSecrets:
      - name: registry-credentials

