apiVersion: servicebinding.io/v1alpha3
kind: ServiceBinding
metadata:
  name: sensors-rmq
spec:
  service:
    apiVersion: rabbitmq.com/v1beta1
    kind: RabbitmqCluster
    name: rabbitmqcluster-sample
  workload:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: sensors
---
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sensors
  labels:
    carto.run/workload-name: sensors
    app.kubernetes.io/component: run
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: 1
    spec:
      containers:
      - name: workload
        image: harbor.vrabbi.cloud/workloads/oss-sensors@sha256:f7b1fc03841cf49bf4cf0b46be2856d94c2202dbc9eab9d58341a5c4f4abdf0b
        securityContext:
          runAsUser: 1000
      imagePullSecrets:
      - name: registry-credentials

