apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: go-tap-app-01
  labels:
    app.kubernetes.io/part-of: hello-world
    carto.run/workload-name: go-tap-app-01
    app.kubernetes.io/component: run
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '1'
    spec:
      containers:
        - name: workload
          image: harbor.eks.vrabbi.cloud/demo/tap-gitops-go-tap-app-01@sha256:063c2ec00c1ee0acb1dc4019415cb1eed84b078a3a51e8f333df58d10319534e
          securityContext:
            runAsUser: 1000
      imagePullSecrets:
        - name: registry-credentials-gitops

